// demo/react19-demo/src/App.tsx
import { useState } from "react";
import "vg/jsx"
import type { ThemeMode, ButtonVariant, ButtonSize, DropdownChangeDetail, InputChangeDetail } from "vg";

const THEME_OPTIONS = [
  { label: "Dark", value: "dark" },
  { label: "Light", value: "light" },
  { label: "Glass", value: "glass" },
  { label: "Cartoon", value: "cartoon" },
];

const VARIANT_OPTIONS = [
  { label: "Primary", value: "primary" },
  { label: "Secondary", value: "secondary" },
  { label: "Ghost", value: "ghost" },
];

const SIZE_OPTIONS = [
  { label: "Small", value: "sm" },
  { label: "Medium", value: "md" },
  { label: "Large", value: "lg" },
];

function App() {
  const [theme, setTheme] = useState<ThemeMode>("dark");
  const [variant, setVariant] = useState<ButtonVariant>("primary");
  const [size, setSize] = useState<ButtonSize>("md");
  const [label, setLabel] = useState("Launch demo");
  const [clicks, setClicks] = useState(0);


  return (
    <vg-theme-provider mode={theme} onvg-change={e=>console.log(e)}>
      <vg-card heading="Theme controls" variant="subtle">
        <vg-dropdown
          label="Theme"
          value={theme}
          options={THEME_OPTIONS}
          onvg-change={(event: CustomEvent<DropdownChangeDetail>) => setTheme(event.detail.value as ThemeMode)}
        >
          <svg slot="prefix" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...{ slot: "prefix" } as any}>
            <circle cx="12" cy="12" r="10"/>
            <path d="M12 2a7 7 0 1 0 10 10"/>
          </svg>
        </vg-dropdown>
        <vg-dropdown
          label="Button variant"
          value={variant}
          options={VARIANT_OPTIONS}
          helperText="Preview updates immediately"
          onvg-change={(event: CustomEvent<DropdownChangeDetail>) => setVariant(event.detail.value as ButtonVariant)}
        />
        <vg-dropdown
          label="Button size"
          value={size}
          options={SIZE_OPTIONS}
          onvg-change={(event: CustomEvent<DropdownChangeDetail>) => setSize(event.detail.value as ButtonSize)}
        />
        <vg-input
          label="Button label"
          value={label}
          placeholder="Type a label"
          helperText="Try updating the label to see changes"
          onvg-change={(event: CustomEvent<InputChangeDetail>) => setLabel(event.detail.value)}
        />
      </vg-card>

      <vg-card heading="Preview" variant="outlined">
        <vg-button
          variant={variant}
          size={size}
          onvg-click={(event) => {
            console.info("onClick called with:", {
              type: event.type,
              detail: event.detail,
              target: event.target && 'tagName' in event.target ? event.target.tagName : undefined,
              currentTarget: event.currentTarget && 'tagName' in event.currentTarget ? event.currentTarget.tagName : undefined,
              timeStamp: event.timeStamp,
              stack: new Error().stack?.split('\n').slice(1, 4)
            });
            // event.stopPropagation();
            setClicks((previous) => previous + 1);
          }}
        >
          {label}
        </vg-button>
        <p role="status">Clicked {clicks} times</p>
      </vg-card>
    </vg-theme-provider>
  );
}

export default App;

// demo/vue-demo/src/App.vue
<script setup>
import { ref } from "vue";
import "vg/vue";
const theme = ref("dark");
const variant = ref("primary");
const size = ref("md");
const label = ref("Launch demo");
const clicks = ref(0);

const themeOptions = [
  { label: "Dark", value: "dark" },
  { label: "Light", value: "light" },
  { label: "Glass", value: "glass" },
  { label: "Cartoon", value: "cartoon" },
];

const variantOptions = [
  { label: "Primary", value: "primary" },
  { label: "Secondary", value: "secondary" },
  { label: "Ghost", value: "ghost" },
];

const sizeOptions = [
  { label: "Small", value: "sm" },
  { label: "Medium", value: "md" },
  { label: "Large", value: "lg" },
];

const onThemeChange = (event) => {
  theme.value = event.detail.value;
};

const onVariantChange = (event) => {
  variant.value = event.detail.value;
};

const onSizeChange = (event) => {
  size.value = event.detail.value;
};

const onLabelChange = (event) => {
  label.value = event.detail.value;
};

const onButtonTick = (event) => {
  clicks.value += 1;
  console.info("Button tick", event.detail);
};
</script>

<template>
  <h1>Vue Demo</h1>
  <vg-theme-provider :mode="theme">
    <vg-card heading="Theme controls" variant="subtle">
      <vg-dropdown
        label="Theme"
        :value="theme"
        :options="themeOptions"
        @vg-change="onThemeChange"
      >
        <svg slot="prefix" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <circle cx="12" cy="12" r="10"/>
          <path d="M12 2a7 7 0 1 0 10 10"/>
        </svg>
      </vg-dropdown>
      <vg-dropdown
        label="Button variant"
        :value="variant"
        :options="variantOptions"
        helper-text="Preview updates immediately"
        @vg-change="onVariantChange"
      ></vg-dropdown>
      <vg-dropdown
        label="Button size"
        :value="size"
        :options="sizeOptions"
        @vg-change="onSizeChange"
      ></vg-dropdown>
      <vg-input
        label="Button label"
        :value="label"
        placeholder="Type a label"
        helper-text="Try updating the label to see changes"
        @vg-change="onLabelChange"
      ></vg-input>
    </vg-card>

    <vg-card heading="Preview" variant="outlined">
      <vg-button
        :variant="variant"
        :size="size"
        @vg-click="onButtonTick"
      >
        {{ label }}
      </vg-button>
      <p role="status">Clicked {{ clicks }} times</p>
    </vg-card>
  </vg-theme-provider>
</template>
